      case 'royal': return Icons.workspace_premium_rounded;
      case 'ninja': return Icons.sports_martial_arts_rounded;
      case 'pirate': return Icons.sailing_rounded;
      case 'wolf': return Icons.nightlight_round;
      case 'diamond': return Icons.diamond_rounded;
      case 'tornado': return Icons.air_rounded;
      case 'demon': return Icons.local_fire_department_rounded;
      case 'falcon': return Icons.radar_rounded;
      case 'cosmic': return Icons.blur_circular_rounded;
