                ElevatedButton.icon(
                  style: ElevatedButton.styleFrom(backgroundColor: Colors.amberAccent),
                  onPressed: () => triggerTest("Karan (Admin)", "royal"),
                  icon: const Icon(Icons.workspace_premium, color: Colors.black),
                  label: const Text("Test 👑 Royal Throne", style: TextStyle(color: Colors.black)),
                ),
                const SizedBox(height: 8),
                ElevatedButton.icon(
                  style: ElevatedButton.styleFrom(backgroundColor: Colors.grey.shade800),
                  onPressed: () => triggerTest("Karan (Admin)", "ninja"),
                  icon: const Icon(Icons.sports_martial_arts, color: Colors.white),
                  label: const Text("Test 🥷 Cyber Ninja"),
                ),
                const SizedBox(height: 8),
                ElevatedButton.icon(
                  style: ElevatedButton.styleFrom(backgroundColor: Colors.blueGrey),
                  onPressed: () => triggerTest("Karan (Admin)", "pirate"),
                  icon: const Icon(Icons.sailing, color: Colors.white),
                  label: const Text("Test 🏴‍☠️ Pirate King"),
                ),
                const SizedBox(height: 8),
                ElevatedButton.icon(
                  style: ElevatedButton.styleFrom(backgroundColor: Colors.indigo),
                  onPressed: () => triggerTest("Karan (Admin)", "wolf"),
                  icon: const Icon(Icons.nightlight, color: Colors.white),
                  label: const Text("Test 🐺 Alpha Wolf"),
                ),
                const SizedBox(height: 8),
                ElevatedButton.icon(
                  style: ElevatedButton.styleFrom(backgroundColor: Colors.cyan),
                  onPressed: () => triggerTest("Karan (Admin)", "diamond"),
                  icon: const Icon(Icons.diamond, color: Colors.black),
                  label: const Text("Test 💎 Diamond Burst", style: TextStyle(color: Colors.black)),
                ),
                const SizedBox(height: 8),
                ElevatedButton.icon(
                  style: ElevatedButton.styleFrom(backgroundColor: Colors.blueGrey.shade400),
                  onPressed: () => triggerTest("Karan (Admin)", "tornado"),
                  icon: const Icon(Icons.air, color: Colors.white),
                  label: const Text("Test 🌪️ Tornado Storm"),
                ),
                const SizedBox(height: 8),
                ElevatedButton.icon(
                  style: ElevatedButton.styleFrom(backgroundColor: Colors.red.shade900),
                  onPressed: () => triggerTest("Karan (Admin)", "demon"),
                  icon: const Icon(Icons.local_fire_department, color: Colors.white),
                  label: const Text("Test 🔥 Hellfire Demon"),
                ),
                const SizedBox(height: 8),
                ElevatedButton.icon(
                  style: ElevatedButton.styleFrom(backgroundColor: Colors.brown),
                  onPressed: () => triggerTest("Karan (Admin)", "falcon"),
                  icon: const Icon(Icons.radar, color: Colors.white),
                  label: const Text("Test 🦅 Royal Falcon"),
                ),
                const SizedBox(height: 8),
                ElevatedButton.icon(
                  style: ElevatedButton.styleFrom(backgroundColor: Colors.deepPurple),
                  onPressed: () => triggerTest("Karan (Admin)", "cosmic"),
                  icon: const Icon(Icons.blur_circular, color: Colors.white),
                  label: const Text("Test 🌌 Cosmic BlackHole"),
                ),
