name: Create Android and Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Prepare Flutter project
        run: |
          mkdir -p lib
          mv main.dart lib/main.dart
          mv entry_animation.dart lib/entry_animation.dart
          flutter create --platforms=android --project-name go_voice_chat .

      - name: Add Firebase file
        run: |
          mkdir -p android/app
          cp google-services.json android/app/google-services.json

      - name: Get packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: go-voice-chat-apk
          path: build/app/outputs/flutter-apk/app-release.apk
